[package]
name = "simple-png"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.71"
miniz_oxide = "0.7.1"
nom = "7.1.3"
once_cell = "1.17.1"
